#!/usr/bin/env bash
#
# tag-release.sh — fully automated release tagging for loomworks.
#
# Usage:  tools/tag-release.sh X.Y.Z
#         tools/tag-release.sh -n | --dry-run X.Y.Z
#         tools/tag-release.sh -h | --help
#         tools/tag-release.sh --version
#
# -n / --dry-run runs every guard and shows exactly what would change
# (real diffs, generated against temp files) but modifies NOTHING and
# does not commit or tag.
# Guarantees that EVERY version number in the repo is consistent before
# creating the release tag:
#
#   1. CMakeLists.txt          project(loomworks VERSION ...) — single source
#   2. build_*/loomworksConfigVersion.cmake — regenerated by reconfiguring
#      each build tree (never hand-edited; written by write_basic_package_version_file)
#   3. CHANGELOG.md            [Unreleased] -> [X.Y.Z] - YYYY-MM-DD
#   4. docs/migration.md       project() example lines
#
# Then commits the bump and creates the annotated tag:
#
#   git commit -m "chore: release vX.Y.Z"
#   git tag -a vX.Y.Z -m "Release vX.Y.Z"
#
# It NEVER pushes.  Review the summary, then push manually
# (git push && git push --tags) after confirming the tag.
#
# Bail-out conditions (any → abort, nothing modified):
#   - argument is not a valid semver X.Y.Z
#   - not on branch `master`
#   - working tree has staged or unstaged changes (untracked files allowed)
#   - tag vX.Y.Z already exists
#   - new version is not strictly greater than the current one
#
set -euo pipefail

NEW_VERSION="${1:-}"
SRC="CMakeLists.txt"
CHANGELOG="CHANGELOG.md"
MIGRATION="docs/migration.md"
DRY_RUN=0

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m(!)\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# render_diff <file> <tmp-file> — print a unified diff of file vs tmp (stdout).
render_diff() {
    if diff -q "$1" "$2" >/dev/null 2>&1; then
        printf '   (dry-run) %-30s no change\n' "$1"
    else
        printf '   (dry-run) %-30s would change:\n' "$1"
        diff -u "$1" "$2" | tail -n +3 | sed 's/^/     /' || true
    fi
}

usage() {
    cat <<'EOF'
tag-release.sh — bump the loomworks version, keep every version number
consistent, then commit and create the annotated release tag.

USAGE
    tools/tag-release.sh X.Y.Z      create release vX.Y.Z
    tools/tag-release.sh -n | --dry-run X.Y.Z
                                    show exactly what would change
                                    (real diffs, temp-file generated)
                                    without modifying/committing/tagging
    tools/tag-release.sh -h | --help
    tools/tag-release.sh --version  print the current version and exit

WHAT IT DOES
    Bumps the version from the current value of the single source of
    truth (project() in CMakeLists.txt) to X.Y.Z, then verifies every
    version location agrees before committing and tagging:

      1. CMakeLists.txt                     project(loomworks VERSION ...)
      2. build_*/loomworksConfigVersion.cmake
                                            regenerated by reconfiguring
                                            each build tree (never
                                            hand-edited — written by
                                            write_basic_package_version_file)
      3. CHANGELOG.md                       [Unreleased] -> [X.Y.Z] - date
      4. docs/migration.md                  project() example lines

    Then:
      git commit -m "chore: release vX.Y.Z"
      git tag -a vX.Y.Z -m "Release vX.Y.Z"

    It NEVER pushes.  Review the summary, then push manually with
    `git push && git push --tags`.

BAIL-OUT CONDITIONS (any -> abort, nothing modified)
    - argument is not a valid semver X.Y.Z
    - not on branch `master`
    - working tree has staged or unstaged changes (untracked files allowed)
    - tag vX.Y.Z already exists
    - new version is not strictly greater than the current one
EOF
}

# Handle -h/--help/--version/--dry-run before anything else (no side effects).
case "${1:-}" in
    -h | --help)
        usage
        exit 0
        ;;
    --version)
        CUR="$(sed -n 's/^project(loomworks VERSION \([0-9][0-9.]*\) LANGUAGES C).*/\1/p' "$SRC")"
        if [[ -n "$CUR" ]]; then
            printf 'loomworks current version: %s\n' "$CUR"
            exit 0
        fi
        die "could not parse current version from $SRC"
        ;;
    -n | --dry-run)
        DRY_RUN=1
        NEW_VERSION="${2:-}"
        ;;
esac

# ---------------------------------------------------------------------------
# 1. Validate the requested version (strict semver)
# ---------------------------------------------------------------------------
if [[ -z "$NEW_VERSION" ]]; then
    usage >&2
    exit 1
fi
if ! [[ "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    die "invalid version '$NEW_VERSION' — expected semver X.Y.Z (e.g. 1.1.0); run '$0 -h' for help"
fi

# ---------------------------------------------------------------------------
# 2. Git preconditions
# ---------------------------------------------------------------------------
say "checking git preconditions"
BRANCH="$(git branch --show-current)"
if [[ "$BRANCH" != "master" ]]; then
    die "must run on branch 'master' (on '$BRANCH')"
fi
if ! git diff --quiet HEAD; then
    die "working tree has changes — commit or stash them first (untracked files are fine)"
fi
if git rev-parse -q --verify "refs/tags/v${NEW_VERSION}" >/dev/null; then
    die "tag v${NEW_VERSION} already exists"
fi

# ---------------------------------------------------------------------------
# 3. Read the current version from the single source of truth
# ---------------------------------------------------------------------------
CURRENT_VERSION="$(sed -n 's/^project(loomworks VERSION \([0-9][0-9.]*\) LANGUAGES C).*/\1/p' "$SRC")"
[[ -n "$CURRENT_VERSION" ]] || die "could not parse current version from $SRC"
say "current version: $CURRENT_VERSION   new version: $NEW_VERSION"

if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
    die "new version equals current version ($CURRENT_VERSION) — nothing to do"
fi
NEWER="$(printf '%s\n%s\n' "$CURRENT_VERSION" "$NEW_VERSION" | sort -V | tail -n1)"
if [[ "$NEWER" != "$NEW_VERSION" ]]; then
    die "new version $NEW_VERSION is not strictly greater than current $CURRENT_VERSION"
fi

# ---------------------------------------------------------------------------
# 4. Update every version location
# ---------------------------------------------------------------------------
say "updating $SRC"
if [[ "$DRY_RUN" -eq 1 ]]; then
    tmp="$(mktemp)"
    sed \
        "s/^project(loomworks VERSION [0-9][0-9.]* LANGUAGES C).*/project(loomworks VERSION ${NEW_VERSION} LANGUAGES C)/" \
        "$SRC" >"$tmp"
    render_diff "$SRC" "$tmp"
    rm -f "$tmp"
else
    sed -i \
        "s/^project(loomworks VERSION [0-9][0-9.]* LANGUAGES C).*/project(loomworks VERSION ${NEW_VERSION} LANGUAGES C)/" \
        "$SRC"
fi

say "updating $CHANGELOG  ([Unreleased] -> [${NEW_VERSION}] - $(date +%F))"
TODAY="$(date +%F)"
awk_bump() { # awk_bump <src> <dst> — [Unreleased] -> [ver] - today transform
    awk -v ver="$NEW_VERSION" -v today="$TODAY" '
        NR == 1 { print; next }                          # keep "# Changelog"
        /^## \[Unreleased\]/ && !done {
            print "## [Unreleased]"; print "";
            print "## [" ver "] - " today;
            done = 1; next
        }
        { print }
    ' "$1" > "$2"
}
if [[ "$DRY_RUN" -eq 1 ]]; then
    tmp="$(mktemp)"
    awk_bump "$CHANGELOG" "$tmp"
    render_diff "$CHANGELOG" "$tmp"
    rm -f "$tmp"
else
    awk_bump "$CHANGELOG" "$CHANGELOG.tmp" && mv "$CHANGELOG.tmp" "$CHANGELOG"
fi

say "updating $MIGRATION (project() example lines)"
if [[ "$DRY_RUN" -eq 1 ]]; then
    tmp="$(mktemp)"
    sed \
        "/^project(/s/VERSION [0-9][0-9.]* LANGUAGES C/VERSION ${NEW_VERSION} LANGUAGES C/" \
        "$MIGRATION" >"$tmp"
    render_diff "$MIGRATION" "$tmp"
    rm -f "$tmp"
else
    sed -i \
        "/^project(/s/VERSION [0-9][0-9.]* LANGUAGES C/VERSION ${NEW_VERSION} LANGUAGES C/" \
        "$MIGRATION"
fi

# ---------------------------------------------------------------------------
# 5. Reconfigure every build tree so the generated ConfigVersion files
#    (build_*/loomworksConfigVersion.cmake) track the new version.  These
#    are written by write_basic_package_version_file at configure time and
#    must never be hand-edited — but they MUST be regenerated before we
#    claim "all version numbers consistent".
# ---------------------------------------------------------------------------
for dir in build build_asan build_tsan build_ubsan build_release build_cmake; do
    if [[ -d "$dir" && -f "$dir/CMakeCache.txt" ]]; then
        say "reconfigure $dir (regenerates ${dir}/loomworksConfigVersion.cmake)"
        if [[ "$DRY_RUN" -eq 1 ]]; then
            printf '   (dry-run) cmake -S . -B %s  [skipped]\n' "$dir"
        else
            cmake -S . -B "$dir" >/dev/null
        fi
    fi
done

if [[ "$DRY_RUN" -eq 1 ]]; then
    cat <<EOF

Dry run complete — nothing was modified, committed, or tagged.
Would have run:
  cmake -S . -B build*                      # regenerate ConfigVersion files
  git add ${SRC} ${CHANGELOG} ${MIGRATION}
  git commit -m "chore: 🏷️ release v${NEW_VERSION}"
  git tag -a v${NEW_VERSION} -m "Release v${NEW_VERSION}"
EOF
    exit 0
fi

# ---------------------------------------------------------------------------
# 6. Verify: every version location must show the new version
# ---------------------------------------------------------------------------
say "verifying version consistency"
check() { # check <description> <file> <regex>
    local desc="$1" file="$2" regex="$3"
    if grep -qE "$regex" "$file"; then
        printf '   ✓ %-55s %s\n' "$desc" "$file"
    else
        die "version mismatch: $desc not found in $file (regex: $regex)"
    fi
}

check "project(VERSION) source of truth" "$SRC" \
    "^project\(loomworks VERSION ${NEW_VERSION} LANGUAGES C\)"
for dir in build build_asan build_tsan build_ubsan build_release build_cmake; do
    if [[ -f "$dir/loomworksConfigVersion.cmake" ]]; then
        check "generated ConfigVersion (${dir})" "$dir/loomworksConfigVersion.cmake" \
            "^set\(PACKAGE_VERSION \"${NEW_VERSION}\"\)"
    fi
done
check "CHANGELOG release section" "$CHANGELOG" "^## \[${NEW_VERSION}\] - ${TODAY}"
check "migration.md loomworks example" "$MIGRATION" \
    "^project\(loomworks VERSION ${NEW_VERSION} LANGUAGES C\)"
check "migration.md ctpool example" "$MIGRATION" \
    "^project\(ctpool VERSION ${NEW_VERSION} LANGUAGES C\)"

say "all version numbers consistent at v${NEW_VERSION}"

# ---------------------------------------------------------------------------
# 7. Commit
# ---------------------------------------------------------------------------
say "committing release bump"
git add "$SRC" "$CHANGELOG" "$MIGRATION"
git commit -m "chore: 🏷️ release v${NEW_VERSION}" >/dev/null
printf '   ✓ commit %s\n' "$(git rev-parse --short HEAD)"

# ---------------------------------------------------------------------------
# 8. Tag (annotated)
# ---------------------------------------------------------------------------
say "creating annotated tag"
git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
printf '   ✓ tag v%s\n' "$NEW_VERSION"

# ---------------------------------------------------------------------------
# 9. Summary + how to proceed
# ---------------------------------------------------------------------------
cat <<EOF

Release v${NEW_VERSION} is ready:
  commit : $(git log -1 --format='%h %s')
  tag    : v${NEW_VERSION} ($(git rev-parse --short "v${NEW_VERSION}"))

Changed files:
  ${SRC}        project() version
  ${CHANGELOG}  [Unreleased] -> [${NEW_VERSION}] - ${TODAY}
  ${MIGRATION}  project() example lines
  build_*/     Regenerated loomworksConfigVersion.cmake

NOT pushed (by design).  After inspecting & verifying, push with:
  git push && git push --tags

Rollback if something is wrong:
  git tag -d v${NEW_VERSION}
  git reset --soft HEAD~1        # un-commit the release bump
EOF