#!/usr/bin/env bash
#
# tag-release.sh — fully automated release tagging for loomworks.
#
# Usage:  tools/tag-release.sh X.Y.Z
#         tools/tag-release.sh -n | --dry-run X.Y.Z
#         tools/tag-release.sh -h | --help
#         tools/tag-release.sh --version
#
# -n / --dry-run is a PURE PREVIEW: it executes nothing and modifies
# nothing.  It only prints the action list — which files would change
# (with old -> new values) and which commands would run.  No guards are
# enforced (dirty tree / branch / existing tag / version order all
# tolerated); a note is printed when the real run would abort.
# Guarantees that EVERY version number in the repo is consistent before
# creating the release tag:
#
#   1. CMakeLists.txt          project(loomworks VERSION ...) — single source
#   2. build_*/loomworksConfigVersion.cmake — regenerated by reconfiguring
#      each build tree (never hand-edited; written by write_basic_package_version_file)
#   3. CHANGELOG.md            [Unreleased] -> [X.Y.Z] - YYYY-MM-DD
#   4. docs/migration.md       project() example lines
#
# Then commits the bump and creates the annotated tag:
#
#   git commit -m "chore: release vX.Y.Z"
#   git tag -a vX.Y.Z -m "Release vX.Y.Z"
#
# It NEVER pushes.  Review the summary, then push manually
# (git push && git push --tags) after confirming the tag.
#
# Bail-out conditions (any → abort, nothing modified):
#   - argument is not a valid semver X.Y.Z
#   - not on branch `master`
#   - working tree has staged or unstaged changes (untracked files allowed)
#   - tag vX.Y.Z already exists
#   - new version is not strictly greater than the current one
#
set -euo pipefail

NEW_VERSION="${1:-}"
SRC="CMakeLists.txt"
CHANGELOG="CHANGELOG.md"
MIGRATION="docs/migration.md"
DRY_RUN=0

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m(!)\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
    cat <<'EOF'
tag-release.sh — bump the loomworks version, keep every version number
consistent, then commit and create the annotated release tag.

USAGE
    tools/tag-release.sh X.Y.Z      create release vX.Y.Z
    tools/tag-release.sh -n | --dry-run X.Y.Z
                                    print WHAT WOULD change (files with
                                    old -> new values) and the commands
                                    that would run, WITHOUT executing
                                    or modifying anything
    tools/tag-release.sh -h | --help
    tools/tag-release.sh --version  print the current version and exit

WHAT IT DOES
    Bumps the version from the current value of the single source of
    truth (project() in CMakeLists.txt) to X.Y.Z, then verifies every
    version location agrees before committing and tagging:

      1. CMakeLists.txt                     project(loomworks VERSION ...)
      2. build_*/loomworksConfigVersion.cmake
                                            regenerated by reconfiguring
                                            each build tree (never
                                            hand-edited — written by
                                            write_basic_package_version_file)
      3. CHANGELOG.md                       [Unreleased] -> [X.Y.Z] - date
      4. docs/migration.md                  project() example lines

    Then:
      git commit -m "chore: release vX.Y.Z"
      git tag -a vX.Y.Z -m "Release vX.Y.Z"

    It NEVER pushes.  Review the summary, then push manually with
    `git push && git push --tags`.

BAIL-OUT CONDITIONS (any -> abort, nothing modified)
    - argument is not a valid semver X.Y.Z
    - not on branch `master`
    - working tree has staged or unstaged changes (untracked files allowed)
    - tag vX.Y.Z already exists
    - new version is not strictly greater than the current one
EOF
}

# Handle -h/--help/--version/--dry-run before anything else (no side effects).
case "${1:-}" in
    -h | --help)
        usage
        exit 0
        ;;
    --version)
        CUR="$(sed -n 's/^project(loomworks VERSION \([0-9][0-9.]*\) LANGUAGES C).*/\1/p' "$SRC")"
        if [[ -n "$CUR" ]]; then
            printf 'loomworks current version: %s\n' "$CUR"
            exit 0
        fi
        die "could not parse current version from $SRC"
        ;;
    -n | --dry-run)
        DRY_RUN=1
        NEW_VERSION="${2:-}"
        ;;
esac

# ---------------------------------------------------------------------------
# 1. Validate the requested version (strict semver)
# ---------------------------------------------------------------------------
if [[ -z "$NEW_VERSION" ]]; then
    usage >&2
    exit 1
fi
if ! [[ "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    die "invalid version '$NEW_VERSION' — expected semver X.Y.Z (e.g. 1.1.0); run '$0 -h' for help"
fi

# ---------------------------------------------------------------------------
# Read the current version from the single source of truth (shared by both
# the dry-run preview and the real run).
# ---------------------------------------------------------------------------
CURRENT_VERSION="$(sed -n 's/^project(loomworks VERSION \([0-9][0-9.]*\) LANGUAGES C).*/\1/p' "$SRC")"
[[ -n "$CURRENT_VERSION" ]] || die "could not parse current version from $SRC"
TODAY="$(date +%F)"

# ---------------------------------------------------------------------------
# Dry-run: pure preview.  Nothing is executed, no file is touched, no git
# command runs.  Only the action list is printed.
# ---------------------------------------------------------------------------
if [[ "$DRY_RUN" -eq 1 ]]; then
    NEWER="$(printf '%s\n%s\n' "$CURRENT_VERSION" "$NEW_VERSION" | sort -V | tail -n1)"
    if [[ "$NEWER" != "$NEW_VERSION" ]]; then
        warn "the real run would ABORT: version $NEW_VERSION is not strictly greater than current $CURRENT_VERSION"
    elif [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
        warn "the real run would ABORT: new version equals current version ($CURRENT_VERSION) — nothing to do"
    fi

    cat <<EOF
Dry run — nothing was executed or modified.

Current version: ${CURRENT_VERSION}   requested: ${NEW_VERSION}

Would change:
  1. ${SRC}                     project() VERSION ${CURRENT_VERSION} -> ${NEW_VERSION}
  2. ${CHANGELOG}               insert "## [${NEW_VERSION}] - ${TODAY}" section under [Unreleased]
  3. ${MIGRATION}               project() example lines ${CURRENT_VERSION} -> ${NEW_VERSION}
  4. build_*/                   regenerate loomworksConfigVersion.cmake
                                (cmake -S . -B <dir> for each configured build tree)

Would run:
  cmake -S . -B build*                      # regenerate ConfigVersion files
  git add ${SRC} ${CHANGELOG} ${MIGRATION}
  git commit -m "chore: 🏷️ release v${NEW_VERSION}"
  git tag -a v${NEW_VERSION} -m "Release v${NEW_VERSION}"
EOF
    exit 0
fi

# ---------------------------------------------------------------------------
# 2. Git preconditions (real run only)
# ---------------------------------------------------------------------------
say "checking git preconditions"
BRANCH="$(git branch --show-current)"
if [[ "$BRANCH" != "master" ]]; then
    die "must run on branch 'master' (on '$BRANCH')"
fi
if ! git diff --quiet HEAD; then
    die "working tree has changes — commit or stash them first (untracked files are fine)"
fi
if git rev-parse -q --verify "refs/tags/v${NEW_VERSION}" >/dev/null; then
    die "tag v${NEW_VERSION} already exists"
fi

say "current version: $CURRENT_VERSION   new version: $NEW_VERSION"

if [[ "$NEW_VERSION" == "$CURRENT_VERSION" ]]; then
    die "new version equals current version ($CURRENT_VERSION) — nothing to do"
fi
NEWER="$(printf '%s\n%s\n' "$CURRENT_VERSION" "$NEW_VERSION" | sort -V | tail -n1)"
if [[ "$NEWER" != "$NEW_VERSION" ]]; then
    die "new version $NEW_VERSION is not strictly greater than current $CURRENT_VERSION"
fi

# ---------------------------------------------------------------------------
# 3. Update every version location
# ---------------------------------------------------------------------------
say "updating $SRC"
sed -i \
    "s/^project(loomworks VERSION [0-9][0-9.]* LANGUAGES C).*/project(loomworks VERSION ${NEW_VERSION} LANGUAGES C)/" \
    "$SRC"

say "updating $CHANGELOG  ([Unreleased] -> [${NEW_VERSION}] - $TODAY)"
awk_bump() { # awk_bump <src> <dst> — [Unreleased] -> [ver] - today transform
    awk -v ver="$NEW_VERSION" -v today="$TODAY" '
        NR == 1 { print; next }                          # keep "# Changelog"
        /^## \[Unreleased\]/ && !done {
            print "## [Unreleased]"; print "";
            print "## [" ver "] - " today;
            done = 1; next
        }
        { print }
    ' "$1" > "$2"
}
awk_bump "$CHANGELOG" "$CHANGELOG.tmp" && mv "$CHANGELOG.tmp" "$CHANGELOG"

say "updating $MIGRATION (project() example lines)"
sed -i \
    "/^project(/s/VERSION [0-9][0-9.]* LANGUAGES C/VERSION ${NEW_VERSION} LANGUAGES C/" \
    "$MIGRATION"

# ---------------------------------------------------------------------------
# 4. Reconfigure every build tree so the generated ConfigVersion files
#    (build_*/loomworksConfigVersion.cmake) track the new version.  These
#    are written by write_basic_package_version_file at configure time and
#    must never be hand-edited — but they MUST be regenerated before we
#    claim "all version numbers consistent".
# ---------------------------------------------------------------------------
for dir in build build_asan build_tsan build_ubsan build_release build_cmake; do
    if [[ -d "$dir" && -f "$dir/CMakeCache.txt" ]]; then
        say "reconfigure $dir (regenerates ${dir}/loomworksConfigVersion.cmake)"
        cmake -S . -B "$dir" >/dev/null
    fi
done

# ---------------------------------------------------------------------------
# 5. Verify: every version location must show the new version
# ---------------------------------------------------------------------------
say "verifying version consistency"
check() { # check <description> <file> <regex>
    local desc="$1" file="$2" regex="$3"
    if grep -qE "$regex" "$file"; then
        printf '   ✓ %-55s %s\n' "$desc" "$file"
    else
        die "version mismatch: $desc not found in $file (regex: $regex)"
    fi
}

check "project(VERSION) source of truth" "$SRC" \
    "^project\(loomworks VERSION ${NEW_VERSION} LANGUAGES C\)"
for dir in build build_asan build_tsan build_ubsan build_release build_cmake; do
    if [[ -f "$dir/loomworksConfigVersion.cmake" ]]; then
        check "generated ConfigVersion (${dir})" "$dir/loomworksConfigVersion.cmake" \
            "^set\(PACKAGE_VERSION \"${NEW_VERSION}\"\)"
    fi
done
check "CHANGELOG release section" "$CHANGELOG" "^## \[${NEW_VERSION}\] - ${TODAY}"
check "migration.md loomworks example" "$MIGRATION" \
    "^project\(loomworks VERSION ${NEW_VERSION} LANGUAGES C\)"
check "migration.md ctpool example" "$MIGRATION" \
    "^project\(ctpool VERSION ${NEW_VERSION} LANGUAGES C\)"

say "all version numbers consistent at v${NEW_VERSION}"

# ---------------------------------------------------------------------------
# 6. Commit
# ---------------------------------------------------------------------------
say "committing release bump"
git add "$SRC" "$CHANGELOG" "$MIGRATION"
git commit -m "chore: 🏷️ release v${NEW_VERSION}" >/dev/null
printf '   ✓ commit %s\n' "$(git rev-parse --short HEAD)"

# ---------------------------------------------------------------------------
# 7. Tag (annotated)
# ---------------------------------------------------------------------------
say "creating annotated tag"
git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
printf '   ✓ tag v%s\n' "$NEW_VERSION"

# ---------------------------------------------------------------------------
# 8. Summary + how to proceed
# ---------------------------------------------------------------------------
cat <<EOF

Release v${NEW_VERSION} is ready:
  commit : $(git log -1 --format='%h %s')
  tag    : v${NEW_VERSION} ($(git rev-parse --short "v${NEW_VERSION}"))

Changed files:
  ${SRC}        project() version
  ${CHANGELOG}  [Unreleased] -> [${NEW_VERSION}] - ${TODAY}
  ${MIGRATION}  project() example lines
  build_*/     Regenerated loomworksConfigVersion.cmake

NOT pushed (by design).  After inspecting & verifying, push with:
  git push && git push --tags

Rollback if something is wrong:
  git tag -d v${NEW_VERSION}
  git reset --soft HEAD~1        # un-commit the release bump
EOF